# Old configuration of the finger robot
# With this config, the zero position is at the negative end stop.
# Use this in case you need the old config for compatibility reasons.

max_current_A: 2.0
safety_kd: [0.08, 0.08, 0.04]
home_offset_rad: [-0.54, -0.17, 0.0]
initial_position_rad: [1.5, 1.5, 3.0]
