can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 1.5
has_endstop: true
calibration:
    torque_ratio: 1.0
    position_tolerance_rad: 0.05
    move_timeout: 2000
safety_kd:
    - 0.08
    - 0.08
    - 0.04
    - 0.08
    - 0.08
    - 0.04
    - 0.08
    - 0.08
    - 0.04
position_control_gains:
    kp: [3, 3, 3, 3, 3, 3, 3, 3, 3]
    kd: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03]

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad:
    - 1.390
    - 1.211
    - 2.144
    - 0.983
    - 1.344
    - 2.221
    - 1.038
    - 1.307
    - 2.782

# Set the initial position such that it is still save when the stage is at the
# highest level.
initial_position_rad:
    - 0
    - -0.9
    - -1.7
    - 0
    - -0.9
    - -1.7
    - 0
    - -0.9
    - -1.7
