can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 2
has_endstop: true
calibration:
    torque_ratio: 0.6
    position_tolerance_rad: 0.05
    move_timeout: 2000
safety_kd:
    - 0.08
    - 0.08
    - 0.04
    - 0.08
    - 0.08
    - 0.04
    - 0.08
    - 0.08
    - 0.04
position_control_gains:
    kp: [3, 3, 3, 3, 3, 3, 3, 3, 3]
    kd: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03]

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
initial_position_rad:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
