can_ports: ["can0", "can1", "can2", "can3", "can4", "can5"]
max_current_A: 2.0
has_endstop: true
calibration:
    endstop_search_torque_Nm: 0.22
    position_tolerance_rad: 0.05
    move_timeout: 2000
safety_kd:
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
    - 0.09
    - 0.09
    - 0.05
position_control_gains:
    kp: [3, 3, 3, 3, 3, 3, 3, 3, 3]
    kd: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03]

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad:
    - 1.210
    - 0.830
    - 2.355
    - 0.885
    - 1.314
    - 2.226
    - 1.420
    - 0.900
    - 2.725

# Set the initial position such that it is still save when the stage is at the
# highest level.
initial_position_rad:
    - 0
    - -0.9
    - -1.7
    - 0
    - -0.9
    - -1.7
    - 0
    - -0.9
    - -1.7
